version: '3.7'

services:

  web:
    build:
      context: TheGuardianAPI
      dockerfile: api.Dockerfile
    image: theguardianapi:1.0
    depends_on:
      - data
    ports:
      - 8000:80
    networks:
      - default
    environment:
      DatabaseConnection: GuardianPostgreSqlDockerCompose
      ConnectionStrings__GuardianPostgreSqlDockerCompose: Host=data;Username=postgres;Password=R3vTra1n1ng
      CorsOrigins__0: http://localhost:4200
      CorsOrigins__1: http://192.168.99.100:4200
      UseHttpsRedirection: 'false'

  data:
    build:
      context: TheGuardianAPI
      dockerfile: db.Dockerfile
    image: anvelez26/theguardiandb:1.0
    ports:
      - 5432:5432
    networks:
      - default


networks:
  default: