version: '3.7'

services:

  web:
    build:
      context: TheGuardianAPI
      dockerfile: api.Dockerfile
    image: anvelez26/theguardianapi:1.0

  data:
    build:
      context: TheGuardianAPI
      dockerfile: db.Dockerfile
    image: anvelez26/theguardiandb:1.0