version: '3.7'

services:

  web:
    build: TheGuardianAPI
    image: 2002-notes-api:1.0
    depends_on:
      - data
    ports:
      - 8000:80
    networks:
      - default
    environment:
      DatabaseConnection: GuardianPostgreSqlDockerCompose
      ConnectionStrings__GuardianPostgreSqlDockerCompose: Host=data;Database=Guardian;Username=postgres;Password=R3vTra1n1ng
      EnsureDatabaseCreated: 'true'
      CorsOrigins__0: http://localhost:4200
      CorsOrigins__1: http://192.168.99.100:4200
      UseHttpsRedirection: 'false'

  data:
    image: postgres:12.0
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: R3vTra1n1ng

networks:
  default: