// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheGuardian.DataAccess;

namespace TheGuardian.DataAccess.Migrations
{
    [DbContext(typeof(GuardianContext))]
    [Migration("20200511190840_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TheGuardian.DataAccess.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<double>("AggClericalStaffRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<double>("AggFacilityRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<double>("AggMedicalStaffRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<double>("AggOverallRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Zip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "621 North Hall Street",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Baylor Scott & White Heart and Vascular Hospital",
                            Phone = "(214) 820-0600",
                            State = "TX",
                            Website = "http://www.baylorhearthospital.com/handler.cfm?event=practice,main",
                            Zip = 75226
                        },
                        new
                        {
                            Id = 2,
                            Address = "2727 East Lemmon Ave.",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Baylor Scott & White Medical Center Uptown",
                            Phone = "(214) 443-3000",
                            State = "TX",
                            Website = "http://www.bmcuptown.com/",
                            Zip = 75204
                        },
                        new
                        {
                            Id = 3,
                            Address = "3500 Gaston Street",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Baylor University Medical Center",
                            Phone = "(214) 820-0111",
                            State = "TX",
                            Website = "http://www.bswhealth.com/locations/dallas/Pages/default.aspx",
                            Zip = 75246
                        },
                        new
                        {
                            Id = 4,
                            Address = "9440 Poppy Drive",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "City Hospital at White Rock",
                            Phone = "(214) 324-6100",
                            State = "TX",
                            Website = "http://cityhospital.co/",
                            Zip = 75218
                        },
                        new
                        {
                            Id = 5,
                            Address = "7 Medical Parkway",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Dallas Medical Center",
                            Phone = "(972) 888-7000",
                            State = "TX",
                            Website = "http://www.dallasmedcenter.com/",
                            Zip = 75234
                        },
                        new
                        {
                            Id = 6,
                            Address = "4500 South Lancaster Road",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Dallas VA Medical Center",
                            Phone = "(214) 742-8387",
                            State = "TX",
                            Website = "http://www.northtexas.va.gov/",
                            Zip = 75216
                        },
                        new
                        {
                            Id = 7,
                            Address = "7777 Forest Lane",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Medical City Dallas",
                            Phone = "(972) 566-700",
                            State = "TX",
                            Website = "http://medicalcityhospital.com/",
                            Zip = 75230
                        },
                        new
                        {
                            Id = 8,
                            Address = "3500 West Wheatland Road",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Methodist Charlton Medical Center",
                            Phone = "(214) 947-7777",
                            State = "TX",
                            Website = "http://www.methodisthealthsystem.org/methodist-charlton-medical-center/",
                            Zip = 75237
                        },
                        new
                        {
                            Id = 9,
                            Address = "1441 North Beckley Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Methodist Dallas Medical Center",
                            Phone = "(214) 947-8181",
                            State = "TX",
                            Website = "http://www.methodisthealthsystem.org/methodist-dallas-medical-center/?L=true",
                            Zip = 75203
                        },
                        new
                        {
                            Id = 10,
                            Address = "9301 North Central Expressway Suite 100",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "North Central Surgical Center",
                            Phone = "(214) 265-2810",
                            State = "TX",
                            Website = "http://www.northcentralsurgical.com/",
                            Zip = 75231
                        },
                        new
                        {
                            Id = 11,
                            Address = "5200 Harry Hines Boulevard",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Parkland Hospital",
                            Phone = "(214) 590-8000",
                            State = "TX",
                            Website = "http://www.parklandhospital.com/",
                            Zip = 75235
                        },
                        new
                        {
                            Id = 12,
                            Address = "8200 Walnut Hill Lane",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Texas Health Dallas",
                            Phone = "(214) 345-6789",
                            State = "TX",
                            Website = "http://www.texashealth.org/dallas/",
                            Zip = 75231
                        },
                        new
                        {
                            Id = 13,
                            Address = "7115 Greenville Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Texas Institute for Surgery",
                            Phone = "(214) 647-5300",
                            State = "TX",
                            Website = "http://www.texasinstituteforsurgery.com/",
                            Zip = 75231
                        },
                        new
                        {
                            Id = 14,
                            Address = "6201 Harry Hines Boulevard",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "William P. Clements Jr. University Hospital",
                            Phone = "(214) 633-5555",
                            State = "TX",
                            Website = "http://utswmed.org/locations/clements/william-p-clements-jr-university-hospital/",
                            Zip = 75390
                        },
                        new
                        {
                            Id = 15,
                            Address = "5151 Harry Hines Boulevard",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Dallas",
                            Name = "Zale Lipshy Pavilion-William P. Clements Jr. University Hospital",
                            Phone = "(214) 645-5555",
                            State = "TX",
                            Website = "http://utswmed.org/locations/zale-lipshy-pavilion/zale-lipshy-pavilion/",
                            Zip = 75390
                        },
                        new
                        {
                            Id = 16,
                            Address = "707 Highlander Boulevard",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Arlington",
                            Name = "Baylor Scott & White Orthopedic and Spine Hospital Arlington",
                            Phone = "(855) 416-7846",
                            State = "TX",
                            Website = "http://baylorarlington.com/",
                            Zip = 76015
                        },
                        new
                        {
                            Id = 17,
                            Address = "3301 Matlock Rd.",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Arlington",
                            Name = "Medical City Arlington",
                            Phone = "(817) 465-3241",
                            State = "TX",
                            Website = "http://medicalcityarlington.com/",
                            Zip = 76015
                        },
                        new
                        {
                            Id = 18,
                            Address = "800 West Randol Mill Road",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Arlington",
                            Name = "Texas Health Arlington Medical Hospital",
                            Phone = "(817) 960-6100",
                            State = "TX",
                            Website = "http://www.texashealth.org/arlington/",
                            Zip = 76012
                        },
                        new
                        {
                            Id = 19,
                            Address = "811 Wright Street",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Arlington",
                            Name = "Texas Health Heart & Vascular Hospital Arlington",
                            Phone = "(817) 960-3500",
                            State = "TX",
                            Website = "http://www.texashealthheartandvascular.org/",
                            Zip = 76012
                        },
                        new
                        {
                            Id = 20,
                            Address = "801 West Interstate 20	Arlington",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Arlington",
                            Name = "USMD Hospital at Arlington",
                            Phone = "(817) 472-3400",
                            State = "TX",
                            Website = "http://www.usmdarlington.com/",
                            Zip = 76017
                        },
                        new
                        {
                            Id = 21,
                            Address = "1400 Eighth Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Baylor Scott & White All Saints Medical Center",
                            Phone = "(817) 926-2544",
                            State = "TX",
                            Website = "http://www.bswhealth.com/locations/fort-worth/Pages/default.aspx",
                            Zip = 76104
                        },
                        new
                        {
                            Id = 22,
                            Address = "1800 Park Place Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Baylor Scott & White Surgical Hospital Fort Worth",
                            Phone = "(682) 703-5600",
                            State = "TX",
                            Website = "http://www.bshfw.com/",
                            Zip = 76110
                        },
                        new
                        {
                            Id = 23,
                            Address = "1500 South Main Street",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "John Peter Smith Hospital",
                            Phone = "(817) 921-3431",
                            State = "TX",
                            Website = "http://www.jpshealthnet.org/",
                            Zip = 76104
                        },
                        new
                        {
                            Id = 24,
                            Address = "3101 North Tarrant Pkwy",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Medical City Alliance",
                            Phone = "(817) 639-1000",
                            State = "TX",
                            Website = "http://medicalcityalliance.com/",
                            Zip = 76177
                        },
                        new
                        {
                            Id = 25,
                            Address = "900 Eighth Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Medical City Fort Worth",
                            Phone = "(817) 877-5292",
                            State = "TX",
                            Website = "http://medicalcityfortworth.com/",
                            Zip = 76104
                        },
                        new
                        {
                            Id = 26,
                            Address = "10864 Texas Health Trail",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Texas Health Alliance",
                            Phone = "(682) 212-2000",
                            State = "TX",
                            Website = "http://www.texashealth.org/alliance/",
                            Zip = 76244
                        },
                        new
                        {
                            Id = 27,
                            Address = "1301 Pennsylvania Avenue",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Texas Health Fort Worth",
                            Phone = "(817) 250-2000",
                            State = "TX",
                            Website = "http://www.texashealth.org/fortworth/",
                            Zip = 76104
                        },
                        new
                        {
                            Id = 28,
                            Address = "6100 Harris Parkway",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Texas Health Southwest",
                            Phone = "(817) 433-5000",
                            State = "TX",
                            Website = "http://www.texashealth.org/southwestfw/",
                            Zip = 76132
                        },
                        new
                        {
                            Id = 29,
                            Address = "5900 Altamesa Boulevard",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "USMD Hospital at Fort Worth",
                            Phone = "(817) 433-9100",
                            State = "TX",
                            Website = "http://www.usmdfortworth.com/",
                            Zip = 76132
                        },
                        new
                        {
                            Id = 30,
                            Address = "3200 North Tarrant Parkway",
                            AggClericalStaffRating = 0.0,
                            AggFacilityRating = 0.0,
                            AggMedicalStaffRating = 0.0,
                            AggOverallRating = 0.0,
                            City = "Fort Worth",
                            Name = "Wise Health Surgical Hospital at Parkway",
                            Phone = "(817) 502-7300",
                            State = "TX",
                            Website = "http://www.wisehealthsurgicalhospital.com/parkway/",
                            Zip = 76177
                        });
                });

            modelBuilder.Entity("TheGuardian.DataAccess.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClericalStaffRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdmittance")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("DateSubmitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FacilityRating")
                        .HasColumnType("integer");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalStaffRating")
                        .HasColumnType("integer");

                    b.Property<double>("OverallRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<string>("ReasonOther")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WrittenFeedback")
                        .IsRequired()
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TheGuardian.DataAccess.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("AccountDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("AccountVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying(16)")
                        .HasMaxLength(16);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<int>("Zip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = true,
                            AccountDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AccountVerified = true,
                            Address = "1001 S Center St",
                            City = "Arlington",
                            Email = "superadmin@gmail.com",
                            FirstName = "Super",
                            LastName = "Admin",
                            Password = "R3vTra1n1ng",
                            State = "TX",
                            Zip = 76010
                        });
                });

            modelBuilder.Entity("TheGuardian.DataAccess.Review", b =>
                {
                    b.HasOne("TheGuardian.DataAccess.Hospital", null)
                        .WithMany("Reviews")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheGuardian.DataAccess.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
